### PR TITLE
Simplified main.py

### PR DESCRIPTION
**Pull request by RealSoerensen**
Simplified the on_message function.
All banned words have been moved to blacklist.txt. Now the bot will read the file on startup and put each word in a list. When event is called it will check the list instead.
Generated requirements.txt for easier installation of libs and updated README accordingly.

### CODE REVIEW

**Comment by BadUserHater** [comment]
Thank you for your contribution, I will go test your changes to see how well they work. If they do work, I will make changes to the github files.
- The Idiot Creature Hater
P.S. We test things before commiting them to the repo cause we do not want to submit something on github that does not work.

**Comment by RealSoerensen** [comment]
I have tested it but go ahead :)

**Comment by BadUserHater** [comment]
I have tried it and it works pretty well. Thanks to this simplier strategy, I am implanting this in other bots I made that does similar ways to this.
Even works with multiple text files for various auto-moderation if you want the bot to send different messages for various auto-moderation like what this bot. Thank you for this simplier live-saving way to do this. Will be updating the source code here soon. After that, I will be closing this thread.
- The Idiot Creature Hater

**Comment by RealSoerensen** [comment]
Hey, again.
I'm not sure what you mean by "Will be updating the source code here soon.". You can just press the merge-button and my code will replace the current :)

**Comment by BadUserHater** [comment]
Unfortunitly after extensive testing, we may have to go back to the orignal version that is more complex cause I tried to do this your way and it only triggers matches EXACTLY like what is in the blacklist. When I do something like: "fgsjghjlg launchmynft.co", it will not trigger anymore which defeats the entire purpose of the bot. So I will close this pull request and proceed to go to the orignal.

**Pull request closed without merging**
